name: Continuous Benchmark
on:
  push:
    branches: 
    - main
  workflow_dispatch:

permissions:
  deployments: write
  contents: write

jobs:
  benchmark_cpu:
    name: CPU Pytest benchmark
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Environment
        run: |
          python -m pip install --upgrade pip
          pip install tensordict-nightly
          pip install pytest pytest-benchmark
      - name: Run benchmarks
        run: |
          cd benchmarks/
          python -m pytest --rank 0 --benchmark-json output.json
      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: CPU Benchmark Results
          tool: 'pytest'
          output-file-path: benchmarks/output.json
          fail-on-alert: true
          alert-threshold: '200%'
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages-benchmark
          auto-push: true

  benchmark_gpu:
    name: GPU Pytest benchmark
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
         - os: linux.4xlarge.nvidia.gpu
           python-version: 3.9
    defaults:
      run:
        shell: bash -l {0}
    container: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Environment
        run: |
          pip install tensordict-nightly
          pip install pytest pytest-benchmark
      - name: Run benchmarks
        run: |
          cd benchmarks/
          python -m pytest --rank 0 --benchmark-json output.json
      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: GPU Benchmark Results
          tool: 'pytest'
          output-file-path: benchmarks/output.json
          fail-on-alert: true
          alert-threshold: '200%'
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages-benchmark
          auto-push: true

    