name: Benchmark main
on:
  push:
    branches: 
    - main
  workflow_dispatch:
jobs:
  benchmark:
    name: Run pytest-benchmark benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run benchmark
        run: |
          pip install tensordict-nightly
          pip install pytest pytest-benchmark
          cd benchmarks/
          pytest --benchmark-json output.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Results
          tool: 'pytest'
          output-file-path: benchmarks/output.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
