name: Continuous Benchmark
on:
  push:
    branches: 
    - main
  workflow_dispatch:

permissions:
  deployments: write
  contents: write
jobs:
  benchmark:
    name: Pytest benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run benchmark
        run: |
          pip install tensordict-nightly
          pip install pytest pytest-benchmark
          cd benchmarks/
          pytest --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Push benchmark results to GitHub Pages
          tool: 'pytest'
          output-file-path: benchmarks/output.json
          fail-on-alert: true
          alert-threshold: '200%'
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages-benchmark
          auto-push: true

    